apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orion-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: apidev.davidbrummy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orion-service-deployment
            port:
              number: 8080

